import jsPDF from "jspdf";

export const generateReceipt = (
  transaction: any
) => {
  const doc = new jsPDF();

  const date =
    new Date(
      transaction.createdAt
    ).toLocaleString();

  doc.setFontSize(22);
  doc.text(
    "CryptoVault",
    20,
    20
  );

  doc.setFontSize(14);
  doc.text(
    "Transaction Receipt",
    20,
    32
  );

  doc.line(
    20,
    38,
    190,
    38
  );

  let y = 55;

  const addRow = (
    label: string,
    value: string
  ) => {
    doc.setFontSize(11);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      `${label}:`,
      20,
      y
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    const lines =
      doc.splitTextToSize(
        value,
        130
      );

    doc.text(
      lines,
      70,
      y
    );

    y +=
      Math.max(
        lines.length * 7,
        10
      );
  };

  addRow(
    "Transaction Type",
    transaction.type
  );

  addRow(
    "Status",
    transaction.status
  );

  addRow(
    "Amount",
    `${transaction.amount} ETH`
  );

  addRow(
    "Network",
    "Ethereum Sepolia"
  );

  addRow(
    "Block Number",
    transaction.blockNumber
      ? transaction.blockNumber.toString()
      : "N/A"
  );

  addRow(
    "Transaction Hash",
    transaction.txHash
  );

  addRow(
    "From Address",
    transaction.fromAddress ||
      "N/A"
  );

  addRow(
    "To Address",
    transaction.toAddress ||
      "N/A"
  );

  addRow(
    "Date",
    date
  );

  y += 10;

  doc.line(
    20,
    y,
    190,
    y
  );

  y += 15;

  doc.setFontSize(10);

  doc.text(
    "Generated by CryptoVault Wallet",
    20,
    y
  );

  doc.text(
    `Receipt Generated: ${new Date().toLocaleString()}`,
    20,
    y + 8
  );

  const fileName =
    `receipt-${transaction.txHash.slice(
      0,
      10
    )}.pdf`;

  doc.save(fileName);
};
